---
deployment:
  tasks:
    - export DEPLOYPATH=/home/jetz7773/public_html/
    - /bin/rm -f $DEPLOYPATH/index.php
    - /bin/cp -f index.html $DEPLOYPATH
    - /bin/cp -f construction.html $DEPLOYPATH
    - /bin/cp -f digital.html $DEPLOYPATH
    - /bin/cp -f creative.html $DEPLOYPATH
    - /bin/cp -f manifest.webmanifest $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
